  <footer>
    <div div class="container">
      <ul class="footerNav">
        <li><a href="index.php">Home</a></li>
        <li><a href="#">Services</a>
          <ul class="footerSubNav">
            <li><a href="mortgage.php">Mortgage</a></li>
            <li><a href="title.php">Title Search</a></li>
            <li><a href="examination.php">Examination</a></li>
            <li><a href="retail.php">Retail Banking</a></li>
            <li><a href="manufacturing.php">Manufacturing</a></li>
          </ul>
        </li>
        <li><a href="#">ITS</a>
          <ul class="footerSubNav">
            <li><a href="evaluation.php">Evaluation</a></li>
            <li><a href="automation.php">Automation</a></li>
            <li><a href="performance.php">Performance</a></li>
            <li><a href="ostesting.php">OS Testing</a></li>
            <li><a href="citesting.php">CI Testing</a></li>
            <li><a href="mantesting.php">Manual Testing</a></li>
          </ul>        
        </li>
        <li><a href="careers.php">Careers</a></li>
       <li><a onclick="window.open('about.php#aboutJMPUS', '_self'); location.reload();" style="cursor:pointer">About JPM</a>
          <ul class="footerSubNav">
           <li><a onclick="window.open('about.php#mission', '_self'); location.reload();" style="cursor:pointer">Mission &amp; Vision</a></li>
          </ul>
        </li>
        <li><a href="contact.php">Contact</a></li> 
      </ul>
      <div id="btmLogo">
        <p class="address">
          115 W. Main St.<br>
          2nd Flr Ste. D<br>
          Trappe, PA. 19426
        </p>
        <img src="images/brand-new-logo-footer.png" style="text-align:center; width:79px; margin:0 auto !important;" alt="Footer JPM US Logo">
      </div>
      <p class="pull-right" style="text-align:right;">
        <a href="#">Back to top</a>
      </p>
      <p style="position:relative;clear:both;font-size:1.5rem; font-color:#CCC;text-align:center;">&middot;&middot;&middot;&middot;
      </p>
      
    </div>
      <p class="navBottom">
        &copy; 2008 JPM Enterprise, Inc
              &middot; All Rights Reserved
      </p>
  </footer>