<header>   
    <div class="navbar-wrapper">
      <div class="container">
      <div class="banner">
        <img src="images/Akashi_Kaikyo_Bridge_banner.png" alt="Bridge Banner" style="clear:none; width:100%; max-height: 125px;">
      </div> 
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="links-wrapper">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="index.php"><img src="images/brand-new-logo-smallest.png" alt="JPM US Shield" class="logoSmall"/></a>
              <a class="navbar-brand" href="index.php"> JPM US</a>
            </div>
            <div class="navbar-collapse collapse">
              <nav class="fltL">
                <ul class="nav navbar-nav"> 
                  <li><a href="index.php">Home</a></li>
                  <li class="activeNav dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="mortgage.php">Mortgage</a></li>
                      <li><a href="title.php" class="activeNav">Title Search</a></li>
                      <li><a href="examination.php">Examination</a></li>
                      <li><a href="retail.php">Retail Banking</a></li>
                      <li><a href="manufacturing.php">Manufacturing</a></li>
                      <li><a href="finance.php">Finance &amp; Accounting</a></li>
                      <li><a href="hr.php">HR Services</a></li>
                      <li><a href="research.php">Research &amp; Analytics</a></li>
                      <li><a href="logistics.php">Logistics</a></li>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fullName">IT Solutions</span><span class="abbrev">ITS</span><b class="caret"></b> </a>
                      <ul class="dropdown-menu">
                        <li role="presentation" class="dropdown-header">QA Solutions</li>
                          <li><a href="evaluation.php">Evaluation Services</a></li>
                          <li><a href="automation.php">Functional Automation</a></li>
                          <li><a href="performance.php">Performance Engineering</a></li>
                          <li><a href="ostesting.php">Open Source Testing Solutions</a></li>
                          <li><a href="citesting.php">Continuous Integration Testing</a></li>
                          <li><a href="mantesting.php">Manual Testing</a></li>
                          <li><a href="training.php">Customized Training Program</a></li>
                          <li><a href="casestudies.php">Case Studies</a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation" class="dropdown-header">ERP Solutions</li>
                          <li><a href="oracle.php">Oracle</a></li>
                          <li><a href="sap.php">SAP</a></li>
                        <li role="presentation" class="divider"></li>
                        <li><a href="mobile.php">Mobile</a></li>
                        <li><a href="web.php">Web</a></li>
                      </ul>
                  </li>
                </ul>
              </nav>
                
              <nav class="fltR">
                <ul class="nav navbar-nav">
                  <li><a href="careers.php">Careers</a></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a onclick="window.open('about.php#aboutJMPUS', '_self'); location.reload();" style="cursor:pointer">About JPM</a></li>
                        <li><a onclick="window.open('about.php#mission', '_self'); location.reload();" style="cursor:pointer">Mission &amp; Vision</a></li>
                      </ul>
                  </li>
                  <li><a href="contact.php">Contact</a></li>
                </ul>
              </nav>
            </div><!--navbar-collapse-->
          </div><!--links-wrapper-->
        </div><!--navbar-->
      </div><!--container-->
    </div><!--navbar-wrapper-->
    <div class="shield" role="img" aria-label="JPM US Shield"></div>
</header>