    <footer>
      <div class="container">
        <ul class="footerNav">
          <li><a href="index.php">Home</a></li>
          <li><a href="services.php">Services</a>
            <ul class="footerSubNav">
              <li><a href="mortgage.php">Mortgage</a></li>
              <li><a href="title.php">Title Search</a></li>
              <li><a href="examination.php">Examination</a></li>
              <li><a href="retail.php">Retail Banking</a></li>
              <li><a href="manufacturing.php">Manufacturing</a></li>

            </ul>
          </li>
          <li><a href="#">ITS</a>
            <ul class="footerSubNav">
              <li><a href="evaluation.php">Evaluation</a></li>
              <li><a href="automation.php">Automation</a></li>
              <li><a href="performance.php">Performance</a></li>
              <li><a href="ostesting.php">OS Testing</a></li>
              <li><a href="citesting.php">CI Testing</a></li>
              <li><a href="mantesting.php">Manual Testing</a></li>
            </ul>        
          </li>
          <li><a href="careers.php">Careers</a></li>
         <li><a href="about.php#aboutJPMUS">About JPM</a>
            <ul class="footerSubNav">
             <li><a href="about.php#mission">Mission &amp; Vision</a></li>
            </ul>
          </li>
          <li><a href="contact.php">Contact</a></li> 
        </ul>
        <div id="btmLogo">
          <p class="address">
            115 W. Main St.<br>
            2nd Flr Ste. D<br>
            Trappe, PA. 19426
          </p>
          <img src="images/brand-new-logo-footer.png" alt="Footer JPM US Logo" >
        </div>
        <p class="pull-right" style="text-align:right;">
          <a href="#">Back to top</a>
        </p>
        <p style="position:relative;clear:both;font-size:1.5rem; font-color:#CCC;text-align:center;">&middot;&middot;&middot;&middot;
        </p>
        
      </div>
      <p class="navBottom">
        &copy; 2008 JPM Enterprise, Inc
          &middot; All Rights Reserved
      </p>
    </footer>